#
#
# Resource.py
# Python implementation of the Class Resource
# Generated by Enterprise Architect
# Created on:      22-????-2014 23:11:22
# Original author: MyGeN
#
#

import sys
try:
    sys.path.index('../')
    pass
except Exception:
    sys.path.append('../')
    pass


class Resource:
    pass
