#######################################################
# 
# Resource.py
# Python implementation of the Class Resource
# Generated by Enterprise Architect
# Created on:      22-ÎåÔÂ-2014 23:11:22
# Original author: MyGeN
# 
#######################################################


class Resource:
    pass