#######################################################
# 
# WorkerManager.py
# Python implementation of the Class WorkerManager
# Generated by Enterprise Architect
# Created on:      22-����-2014 23:11:22
# Original author: MyGeN
# 
#######################################################

from Common.ThreadBase import ThreadBase

class WorkerManager(ThreadBase):
    pass
