#
#
# Worker.py
# Python implementation of the Class Worker
# Generated by Enterprise Architect
# Created on:      22-����-2014 23:11:22
# Original author: MyGeN
#
#

import sys
try:
    sys.path.index('../')
    pass
except Exception:
    sys.path.append('../')
    pass

from html.parser import HTMLParser


class Worker(HTMLParser):

    '''需要读取配置，获取需要爬的xpath集合'''

    def __init__(self):
        HTMLParser.__init__(self)
        pass

    def handle_starttag(self, tag, attrs):
        pass

    def handle_endtag(self, tag):
        pass

    def handle_data(self, data):
        pass

    pass
