#
#
# Worker.py
# Python implementation of the Class Worker
# Generated by Enterprise Architect
# Created on:      22-����-2014 23:11:22
# Original author: MyGeN
#
#

import sys
try:
    sys.path.index('../')
    pass
except Exception:
    sys.path.append('../')
    pass

from bs4 import BeautifulSoup
from html.parser import HTMLParser


class Worker():
  def __init__(self):
    self.soup = BeautifulSoup()
    pass
  
  def Feed(self,htmlMarkup):
    # Read rules in config file 
    # filter the tags by rules
    # build entity with html content
    # return the entity
    if self.soup:
      self.soup.find()
    pass
