#######################################################
# 
# Feeder.py
# Python implementation of the Class Feeder
# Generated by Enterprise Architect
# Created on:      22-05-2014 23:10:09
# Original author: MyGeN
# 
#######################################################

from Common.ThreadBase import ThreadBase

class Feeder(ThreadBase):
    def __init__(self):
        pass
    
    def GetSpider(self,name):
        pass

    def SendSpider(self,pay):
        pass
