#######################################################
# 
# Spider.py
# Python implementation of the Class Spider
# Generated by Enterprise Architect
# Created on:      22-05-2014 23:10:09
# Original author: MyGeN
# 
#######################################################
import urllib.request


class Spider(object):
    def __init__(self, feeder):
        self.__feeder = feeder
        pass

    def Feed(self, url):
        self.__url = url
        pass

    def Go(self):
        req = urllib.request.urlopen(self.__url)
        data = req.read().decode('utf-8')
        req.close()
        return data
