#######################################################
# 
# Spider.py
# Python implementation of the Class Spider
# Generated by Enterprise Architect
# Created on:      22-05-2014 23:10:09
# Original author: MyGeN
# 
#######################################################
import sys
try:
    sys.path.index('../')
    pass
except Exception:
    sys.path.append('../')
    pass

import urllib.request
from Common.ThreadBase import ThreadBase
from Common.Msg import *

class SPIDERFLAG(object):
    RUN = 0
    REDAY = 1
        

class Spider(ThreadBase):
    def __init__(self, spiderName):
        ThreadBase.__init__(self,spiderName)
        self.__status = SPIDERFLAG.REDAY
        pass

    def Feed(self, url):
        self.__status = SPIDERFLAG.RUN
        self.__url = url
        pass

    def Go(self):
        self.start()
        return data

    def run(self):
        req = urllib.request.urlopen(self.__url)
        data = req.read().decode('utf-8')
        req.close()
        msg = Msg(self.ModelName,)
        self.__status = SPIDERFLAG.REDAY
        pass

    def GetSpiderStatus(self):
        return self.__status
        pass
