#
#
# DataManager.py
# Python implementation of the Class DataManager
# Generated by Enterprise Architect
# Created on:      22-����-2014 23:10:40
# Original author: MyGeN
#
#

import sys
try:
    sys.path.index('../')
    pass
except Exception:
    sys.path.append('../')
    pass

from Common.ThreadBase import ThreadBase


class DataManager(ThreadBase):
    pass
