#
#
# SaveDataToDB.py
# Python implementation of the Class SaveDataToDB
# Generated by Enterprise Architect
# Created on:      22-ÎåÔÂ-2014 23:10:40
# Original author: MyGeN
#
#

import sys
try:
    sys.path.index('../')
    pass
except Exception:
    sys.path.append('../')
    pass

from DataSave.SaveDataBase import SaveDataBase


class SaveDataToDB(SaveDataBase):
    pass
