#######################################################
# 
# SaveDataToFile.py
# Python implementation of the Class SaveDataToFile
# Generated by Enterprise Architect
# Created on:      22-ÎåÔÂ-2014 23:10:40
# Original author: MyGeN
# 
#######################################################
from DataSave.SaveDataBase import SaveDataBase

class SaveDataToFile(SaveDataBase):
    pass