#
#
# SaveDataBase.py
# Python implementation of the Class SaveDataBase
# Generated by Enterprise Architect
# Created on:      22-????-2014 23:10:40
# Original author: MyGeN
#
#

import sys
try:
    sys.path.index('../')
    pass
except Exception:
    sys.path.append('../')
    pass


class SaveDataBase:
    pass
