#
#
# SaveDataToFile.py
# Python implementation of the Class SaveDataToFile
# Generated by Enterprise Architect
# Created on:      22-????-2014 23:10:40
# Original author: MyGeN
#
#

import sys
try:
    sys.path.index('../')
    pass
except Exception:
    sys.path.append('../')
    pass

from DataSave.SaveDataBase import SaveDataBase


class SaveDataToFile(SaveDataBase):
    pass
