#######################################################
# 
# SaveDataBase.py
# Python implementation of the Class SaveDataBase
# Generated by Enterprise Architect
# Created on:      22-ÎåÔÂ-2014 23:10:40
# Original author: MyGeN
# 
#######################################################


class SaveDataBase:
    pass